export const projects = [
 {
 id: 1,
 title:"Sophia (Hybrid RAG System)",
 description:
"An AI assistant platform where users can create and train custom personas using their own data. Built with Next.js, LangChain, Azure AI Search, PostgreSQL, and Neo4j.",
 longDescription:
"Built an AI assistant platform where users can create and train custom personas using their own data. Designed a hybrid RAG architecture combining knowledge graph (Neo4j) and vector database to enhance accuracy. Reduced hallucination rate by improving retrieval accuracy via hybrid RAG (vector + graph-based retrieval).",
 image:"/thumbnails/study-buddy.png",
 images: [
"/projects/study-buddy/home.png",
"/projects/study-buddy/dashboard.png",
"/projects/study-buddy/preview.png",
"/projects/study-buddy/chat_interface.png",
 ],
 tech: [
"Next.js",
"LangChain",
"Azure AI Search",
"PostgreSQL",
"Neo4j",
"TypeScript",
 ],
 github:"https://github.com/Dharshansk16",
 live:"https://github.com/Dharshansk16",
 color:"",
 category:"AI/ML",
 status:"Completed",
 year:"2024",
 duration:"2 months",
 team:"Solo Project",
},
 {
 id: 2,
 title:"Hackfest '26 (Evaluation System)",
 description:
"A scalable evaluation interface built to handle 3000+ participants and 600+ submissions, reducing evaluation time by 60%+.",
 longDescription:
"Built a scalable evaluation interface handling 3000+ participants and 600+ submissions, reducing evaluation time by 60%+ via unified workflows. Implemented score normalisation logic to mitigate bias between strict and lenient judges, ensuring fair and consistent evaluation.",
 image:"/thumbnails/next-auction.png",
 images: [
"/projects/next-auction/live-auction.png",
"/projects/next-auction/manage-team.png",
"/projects/next-auction/all-players.png",
"/projects/next-auction/settings.png",
 ],
 tech: ["Next.js","TypeScript","TailwindCSS","Drizzle","PostgreSQL"],
 github:"https://github.com/Dharshansk16",
 live:"https://github.com/Dharshansk16",
 color:"",
 category:"Full Stack",
 status:"Completed",
 year:"2024",
 duration:"1 month",
 team:"Team",
},
 {
 id: 3,
 title:"Study Buddy",
 description:
"Study Buddy is a web app that lets students upload PDFs and chat with an AI to get answers based on the document's content. Built with Next.js and Django Rest Framework.",
 longDescription:
"Study Buddy is a full-stack web application that allows students to upload PDF documents and engage in a chat interface powered by GEMINI, where they can ask questions based on the content of the uploaded PDF. Built with Next.js on the frontend and Django Rest Framework on the backend, Study Buddy is designed to enhance students' productivity by offering an intuitive way to interact with study materials.",
 image:"/thumbnails/study-buddy.png",
 images: [
"/projects/study-buddy/home.png",
"/projects/study-buddy/dashboard.png",
"/projects/study-buddy/preview.png",
"/projects/study-buddy/chat_interface.png",
 ],
 tech: [
"Next.js",
"TypeScript",
"Django",
"Python",
"LangChain",
"GEMINI",
"VectorDB",
"TailwindCSS",
"PostgreSQL",
 ],
 github:"https://github.com/Dharshansk16/Study_Buddy",
 live:"https://github.com/Dharshansk16/Study_Buddy",
 color:"",
 category:"Full Stack",
 status:"Completed",
 year:"2024",
 duration:"1 month",
 team:"Solo Project",
}
];
