export const projects = [
  {
    id: 1,
    title: "Study Buddy",
    description:
      "Study Buddy is a web app that lets students upload PDFs and chat with an AI to get answers based on the document's content. Built with Next.js and Django Rest Framework.",
    longDescription:
      "Study Buddy is a full-stack web application that allows students to upload PDF documents and engage in a chat interface powered by GEMINI, where they can ask questions based on the content of the uploaded PDF. Built with Next.js on the frontend and Django Rest Framework on the backend, Study Buddy is designed to enhance students' productivity by offering an intuitive way to interact with study materials.",
    image: "/thumbnails/study-buddy.png",
    images: [
      "/projects/study-buddy/home.png",
      "/projects/study-buddy/dashboard.png",
      "/projects/study-buddy/preview.png",
      "/projects/study-buddy/chat_interface.png",
    ],
    tech: [
      "Next.js",
      "TypeScript",
      "Django",
      "Python",
      "LangChain",
      "GEMINI",
      "VectorDB",
      "TailwindCSS",
      "PostgreSQL",
    ],
    github: "https://github.com/Dharshansk16/Study_Buddy",
    live: "https://github.com/Dharshansk16/Study_Buddy",
    color: "from-black via-gray-700 to-white",
    category: "Full Stack",
    status: "Completed",
    year: "2024",
    duration: "1 month",
    team: "Solo Project",
  },
  {
    id: 2,
    title: "Next Auction",
    description:
      "Next Auction is a modern web platform built with Next.js, designed to simplify and streamline cricket tournament auctions. From real-time auction updates to team management, settings control, and budget tracking, it provides all the tools needed to run a smooth and transparent auction.The platform was successfully used in the Baarish Cup cricket auction, where it significantly reduced manual errors, saved time, and boosted overall efficiency. With rich insights and a user-friendly dashboard, Next Auction empowers organizers to manage every aspect of the auction process with confidence and clarity",
    longDescription: "",
    image: "/thumbnails/next-auction.png",
    images: [
      "/projects/next-auction/live-auction.png",
      "/projects/next-auction/manage-team.png",
      "/projects/next-auction/all-players.png",
      "/projects/next-auction/settings.png",
    ],
    tech: ["React", "Nextjs", "Tailwind CSS", "Shadcn UI", "Typescript"],
    github: "https://github.com",
    live: "https://demo.com",
    color: "from-black via-gray-700 to-white",
    category: "AI/ML",
    status: "In Progress",
    year: "2024",
    duration: "1 week",
    team: "Solo",
  },
  {
    id: 3,
    title: "NUSIA",
    description:
      " NUSIA-Nitte University Student Information Access: A student management project designed to streamline the process of managing student information.",
    longDescription:
      "NUSIA-Nitte University Student Information Access:  A student management project designed to streamline the process of managing student information for authorized users, such as teachers and professors. This project is part of my college internship and is built using Django and Bootstrap.",
    image: "/thumbnails/nusia.png",
    images: [
      "/projects/nusia/home.png",
      "/projects/nusia/dashboard.png",
      "/projects/nusia/add.png",
      "/projects/nusia/update.png",
    ],
    tech: ["Django", "Bootstrap", "Chartjs", "CSS", "JWT"],
    github: "https://github.com/Dharshansk16/NUSIA",
    live: "https://github.com/Dharshansk16/NUSIA",
    color: "from-black/70 via-white/60 to-black/70",
    category: "Web Development",
    status: "Completed",
    year: "2024",
    duration: "1 month",
    team: "Solo Project",
  },
  {
    id: 4,
    title: "Blockchain DeFi Platform",
    description:
      "A decentralized finance platform built on Ethereum, featuring yield farming, staking, and NFT marketplace.",
    longDescription:
      "Enter the world of decentralized finance with this comprehensive DeFi platform. Built on Ethereum blockchain using Solidity smart contracts, it offers yield farming opportunities, staking mechanisms, and an integrated NFT marketplace. The platform ensures security through extensive testing and audit processes.",
    image: "/placeholder.svg?height=400&width=600&text=DeFi+Platform",
    images: [
      "/placeholder.svg?height=400&width=600&text=Trading+Interface",
      "/placeholder.svg?height=400&width=600&text=Staking+Pool",
      "/placeholder.svg?height=400&width=600&text=NFT+Marketplace",
      "/placeholder.svg?height=400&width=600&text=Wallet+Connect",
    ],
    tech: ["Solidity", "Web3.js", "React", "Hardhat", "IPFS", "MetaMask"],
    github: "https://github.com",
    live: "https://demo.com",
    color: "from-orange-500 via-red-500 to-pink-500",
    category: "Blockchain",
    status: "Beta",
    year: "2024",
    duration: "5 months",
    team: "3 Developers",
    views: 1567,
    likes: 198,
    stars: 4.6,
  },
];
